### ISSUE TITLE
Update for 3.14

### ISSUE THREAD

**Issue by 0X1A** [tommie-lie/gnome-shell-extension-redshift#6]
Is there any chance this can get updated to 3.14?

**Comment by achadwick** [comment]
Artists will need this switch somewhere. It's useful to temporarily disable redshift when doing artwork.

**Comment by malarkannan** [comment]
@mbanck same here, wish this extension is supported on gnome 3.20 now that it has been released.

**Comment by jrobeson** [comment]
@malarkannan : gnome 3.20 support is a separate ticket #20

**Comment by jrobeson** [comment]
this ticket title is truly outdated tho.

**Comment by lightonflux** [comment]
Is gnome 3.14 used in any LTS distro?

**Comment by zedinosaur** [comment]
@lightonflux Yes, in Debian Jessie.
